### ISSUE TITLE
RepeatMasker genome1.fa -lib library.fa -pa 8

### ISSUE THREAD

**Issue by ld9866** [Dfam-consortium/TETools#16]
$ RepeatMasker genome1.fa [-lib library.fa] [-pa 8]
Hello, the example you put on the website, I don't know what this - lib library. fa refers to?
If I have an assembled pig genome, how should I set up library.fa in this place?

**Comment by jebrosen** [comment]
You can use the `RepeatMasker -help` command to find more detailed explanations of these options, including the `-lib` option and how to use a custom `library.fa` file.

I'm going to close this issue since it's not really a question about the TE Tools container, but please feel free to reply here if you have further questions about this!
