### ISSUE TITLE
Not sure how I should deal with the forecast results and the results of the existing database

### ISSUE THREAD

**Issue by ld9866** [Dfam-consortium/TETools#20]
Hello! Thank you very much for developing such good software. Recently, I have a few unsure questions that I would like to ask you.
We assembled a genome and we made predictions through RepeatModeler software. We ran the RepeatMasker software using the predicted set of repeat sequences (***-family. fa) and found that the repeat sequence of the genome was as high as 38.75 %. This may be right. However, we also used the repetitive sequences of existing species based on dfam and repbase databases, and we found that the repetitive sequences reached 41.31%.  I also tried to merge the prediction results with the results of the database and found that the repetitive sequence was as high as 44.71%. This result was much higher than our expectations. This may be wrong.
I am not sure which result we should use for subsequent genome annotation analysis, I would like to ask you.
Looking forward to hearing from you!

**Comment by jebrosen** [comment]
Hi,

That is a good question. But, this does not necessarily sound like a problem. RepeatModeler processes samples of a particular genome assembly, so it may miss some specific TEs due to "bad luck" or due to limitations in the sequencing or assembly process that make them difficult to recognize. Dfam and RepBase include TE families from ancestral species, which are known from prior research but are too fragmented or mutated to meet RepeatModeler's thresholds. Due to the different limitations of the two approaches, it can be more informative to combine the newly discovered elements into one library as you did.

Does this seem likely to explain the differences in your results?

**Comment by ld9866** [comment]
Hello!
Very happy to receive your reply!
You said that we used the combined collection as the input file. We tried it, and the result was very confusing to me.
We use the combined (cat ) result "the prediction result of RepeatModeler, dfam and repbase" and the result  is 44.71% as l said before.
If we first use the prediction result of RepeatModeler to shield the repetitive sequence., and then the shielded sequence again run the set of dfam and repbase the result is 43.64%. We first use the set of dfam and repbase and then run the the prediction result of RepeatModeler, the result is 43.91%.
I would like to ask which method should we use?
The combine is a very confusing place for us. What causes such a deviation?
Looking forward to hearing from you!

**Comment by jebrosen** [comment]
> The combine is a very confusing place for us. What causes such a deviation?

Running RepeatMasker twice with two different libraries will likely produce different results from running it once with a combined library. For example, the two repeat libraries could include similar but not identical families or fragments of families. In this situation, the first RepeatMasker run might mask most of an element. Then, the second RepeatMasker run might not recognize the leftover part because it is too short. So, each RepeatMasker run can affect the other run depending on the order. If RepeatMasker starts with a combined library instead, it can more effectively discover the elements from both libraries at once.

> I would like to ask which method should we use?

The most appropriate method will depend on your goal and how well the RepeatModeler libraries came out for your species. For example, one method might mask more sequence, while another could produce a cleaner annotation with fewer fragments or more well-known names.

I hope this explanation helps you to decide what method to use!

**Comment by ld9866** [comment]
Thank you very much for your valuable advice and patient help. 
Your help is really of great significance to our work.
We decided to "combine" it with the method you said. 
Maybe this is a more appropriate method.
Sincerely yours

**Comment by jebrosen** [comment]
Glad to hear! It seems like this question has been answered, but please re-open this or a new issue if you have more.
