### ISSUE TITLE
hangup error on round5 of RepeatModeler on singularity sif v1.8, v1.85

### ISSUE THREAD

**Issue by XuewenWangUGA** [Dfam-consortium/TETools#30]
**Describe the bug**

The container .sif release version v1.8, and v1.85 have error on round5 on Singularity CE v4.0.0 and singularity 3.11
Platform: Linux Ubuntu 20.04, a single computer
command: singularity --debug exec --bind /usr/lib/locale/,/media/xx/data12T /media/xx/data12T/tetools/dfam-tetools-latest.sif RepeatModeler -database genome1 -LTRStruct -threads 20

error inforamtion: 
Warning: [Query 4144-4145] Query_1 gi|4144 gi|9:40001-80000: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 

tetools_sif.sh: line 74: 29800 Hangup                  singularity --debug exec --bind /usr/lib/locale/,/media/xx/data12T /media/xx/data12T/tetools/dfam-tetools-latest.sif RepeatModeler -database genome1 -LTRStruct -threads 20

**Comment by asgray** [comment]
Hi, sorry for the delay. I was able to run the -LTRStruct command on the latest version of the container, but let me know if this is still an issue. 
One thing that stands out to me is the bind command. Binds take the form `-B <host path>:<container path>`, so I don't thing the command you've shared is doing anything. 
Otherwise, there may be an issue with the input files.
