### ISSUE TITLE
Problems configuring RepeatClasifier on docker.

### ISSUE THREAD

**Issue by matthew-ackerman** [Dfam-consortium/TETools#36]
When classifying repeats for Daphnia pulex, a Crustacean, I get >95% unknown families. I've downloaded dfam38_full.8.h5, and have dfam38_full.0.h5 in the RepeatMasker directory. I delete rmlib.config, and when I run ./tetoolsDfamUpdate.pl it seems to correctly detect the dfam library. I set the environmental variable, but when I run RepeatClassifier I still get mostly unknowns. Does RepeatClassifier use RepeatMasker's library? Is there some step I am forgetting? Thanks in advance!

**Comment by asgray** [comment]
Hi, can you provide the command you used to invoke RepeatClassifier? The first thing I want to confirm is that the configured library is being mounted into the container properly. 

Another possible problem is that the automatic update script only extracts the curated families from the .h5 files. It's possible that it's just not including the families that would be useful to you, and if that's the case I can help work around that.

**Comment by matthew-ackerman** [comment]
I use "singularity shell --bind /mnt/pixstor/data/magmt/:/home/magmt/data2
--bind
/mnt/pixstor/sxwf7-lab/RepeateModeler/Libraries:/opt/RepeatMasker/Libraries
~/data/singularity/tetools_latest.sif" to start the container, then delete
/opt/RepeatMasker/Libraries/famdb/rmlib.config then run ./tetoolsDfamUpdate.pl.
tetoolsDfamUpdate seems to see both partitions (it says "2 Partitions
Present"), and then I set the environment variable "export
LIBDIR=/path/to/Libraries".

I then run RepeatClassifier with "RepeatClassifier -consensi my-families.fa"

-Matt

**Comment by asgray** [comment]
A read-only file system could certainly be causing issues. `tetoolsDfamUpdate.pl` rewrites `/opt/RepeatMasker/Libraries/RepeatMasker.lib`, so you could confirm if that's working by checking the timestamp with `ls -al`. 
Can you share the error message when you use the `shell -w` command?

**Comment by matthew-ackerman** [comment]
Sorry to message you again. I was investigating the 'not writable' angle by
creating an image that loads properly with the shell -w command. I did this
by executing "singularity build --sandbox writable_tetools.sif
/home/magmt/data/singularity/tetools_latest.sif". This writable sif loads
properly with the shell -w command, and I verified that it is writable by
making files in the root directory. In this writable image, I
ran tetoolsDfamUpdate.pl as previously specified and it does update the
file RepeatMasker.lib, but I'm still getting mostly unknowns. I may try
downloading a few more dfam38 libraries, but I'm pretty sure Daphnia
(branchiopod crustaceans) belong in dfam38_full.8.h5. Any other ideas?

-Matt

**Comment by asgray** [comment]
Thanks for confirming that the container is working. It looks like the issue is that `tetoolsDfamUpdate.pl` is only importing curated families into `RepeatMasker.lib`, and since there are no curated Daphnia families, it makes sense that you're not seeing any additional hits. To work around this, one solution is to use `famdb.py` to directly query the data you need.

First, I ran a few lineage queries to confirm what is in the FamDB files:
```
python3 famdb.py -i ./dfam38_full lineage -d daphnia
6668 Daphnia(8) [0]
├─6669 Daphnia pulex(8) [0]
└─35523 Daphnia pulicaria(8) [937]
```
```
python3 famdb.py -i ./dfam38_full lineage -d --curated daphnia
6668 Daphnia(8) [0]
├─6669 Daphnia pulex(8) [0]
└─35523 Daphnia pulicaria(8) [0]
```
This confirms that there are 937 uncurated families in file 8, though all are from _Daphnia pulicaria_. To extract them, you can use the `families -f fasta_name` command, and append them to your `RepeatMasker.lib`. The following command should generate the FASTA output from FamDB, prepend a new line to it, and concatenate it to `RepeatMasker.lib`.

```
python3 <host path to /RepeatMasker>/famdb.py -i <host path to /RepeatMasker>/Libraries/famdb families -d -f fasta_name daphnia | (echo && cat) >> <host path to /RepeatMasker>/Libraries/RepeatMasker.lib
```

More information regarding FamDB commands can be found [here](https://github.com/Dfam-consortium/FamDB). If you need to add other FamDB files, just be aware that `tetoolsDfamUpdate.pl` will overwrite any changes you make to `RepeatMasker.lib`. You may choose to run `tetoolsDfamUpdate.pl` anyway, but if not you might need to edit `rmlib.config` by hand. If `tetoolsDfamUpdate.pl` is rerun, be sure to only export uncurated families from FamDB to avoid doubling up curated families in `RepeatMasker.lib`.

Hopefully that  produces better results for you, but let me know either way.

**Comment by matthew-ackerman** [comment]
Sorry, you may be right that this should be closed, but I just got around
to running your fix (I'd been messing with Transposon Ultimate) and I'm not
getting what I want yet. I could still be doing something stupid.

-Matt

**Comment by asgray** [comment]
Sorry, I just closed it because of inactivity.
Either way, it's sounding less like an issue with TETools, and more like an
issue with RepeatClassifier.

If you like, you can send your data to us, and we can try to run it against
all of Dfam to see what we can find. I'm not super familiar with
RepeatClassifier, but you could send it to me or to the author of
RepeatClassifier:

agray at systemsbiology.org
or
rhubley at systemsbiology.org

as you prefer.
