### ISSUE TITLE
Bump version to 2.0

### ISSUE THREAD

**Issue by heavywatal** [Dfam-consortium/TETools#38]
**Describe the bug**

TETools 1.88 looks like not just another release after 1.87. Users should be given a better chance to notice that it comes with breaking changes in FamDB 1.0, and is 10 times bigger in size.

**To Reproduce**

`docker pull dfam/tetools:1`
Surprise!

**Expected behavior**

TETools with RepeatMasker >=4.1.6 and FamDB >=1.0 should be tagged with `2`.
The tag `1` should point to `1.87`, not `1.88`.

**Comment by rmhubley** [comment]
You bring up a good point about the scale of the changes.  The change to a partitioned format within the sub-package famdb has caused some grief due to the root partition being large.  This is more of an issue with the FamDB/RepeatMasker projects and the current plan is to remedy this in the next release by producing a minimal FamDB root partition.

For TEtools it doesn't make much sense to use semantic versioning due to the breadth of software included.  For example, the container may bump up one package by a patch and yet another by a major value and yet the overall changes to the end user may be minimal if they are only using RepeatMasker.  There isn't a clear breaking/minor/patch distinction in what is included and the use-cases are not clearly nailed down.  That said, we will consider increasing the major version number in the future when making any large organizational changes to what is packaged and the overall jump in size.
