### ISSUE TITLE
Command line fasta file scaffolds_final.fa does not exist!

### ISSUE THREAD

**Issue by austinchipps** [Dfam-consortium/TETools#39]
Hi all,

I'm running RepeatModeler using singularity with command: 

**singularity run dfam-tetools-latest.sif BuildDatabase -name myDB scaffolds_final.fa**

However, when I execute the command on my university's HPC, I receive the error: 

**Command line fasta file scaffolds_final.fa does not exist!**

I should mention that when I run: 

**singularity run dfam-tetools-latest.sif BuildDatabase -h**

I receive the help documentation, as expected. Any suggestions?

Thank you!

**Comment by asgray** [comment]
My equivalent of your command works for me:
```
singularity run ../../projects/TETools/tetools BuildDatabase -name myDB test_db-families.fa 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_CTYPE = "en_US.UTF-8",
        LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Building database myDB:
  Reading test_db-families.fa...
Number of sequences (bp) added to database: 8 ( 7939 bp )
```
So the first thing I would check is that you have all the permissions you need on the HPC. You'll need read permissions on your input file, as well as write permissions in your working directory for the database files. 

Additionally, singularity usually automatically binds the working directory into the container, but some admin groups choose to disable that feature. You can test this by entering the container and checking if your working directory is still visible:
```
# in your case:
singularity shell dfam-tetools-latest.sif
# then
ls -al
```
If it turns out that you don't have automatic binding on, you'll have to do it manually with something like this:
```
singularity run -B $(pwd):/opt/src dfam-tetools-latest.sif BuildDatabase -name myDB scaffolds_final.fa
```
You can read more about binding [here](https://docs.sylabs.io/guides/3.0/user-guide/bind_paths_and_mounts.html) if needed. 

Let me know if it works !

**Comment by austinchipps** [comment]
Hi Anthony,

Thank you so much for your quick reply. It was definitely an issue with the automatic binding being turned off. It is fixed now and working perfectly. Thank you again for your help!

Austin
