### ISSUE TITLE
Taxonomy::new() needs a path for a famdb directory!

### ISSUE THREAD

**Issue by andresfeliper3** [Dfam-consortium/TETools#41]
I'm trying to use RepeatMasker and execute it for a chromosome sequence that is in fasta format but I'm getting this message: Taxonomy::new() needs a path for a famdb directory!

I pulled the docker image dfam/tetools.
I cloned this repository.
I executed the dfam-tetools.sh file and entered the container created with the image.
I'm entering: RepeatMasker Libraries/c_elegans_chromosome_I.fasta
Libraries/c_elegans_chromosome_I.fasta is the path of the sequence I want to use.

And I'm getting:
RepeatMasker version 4.1.6
Search Engine: NCBI/RMBLAST [ 2.14.1+ ]
Taxonomy::new() needs a path for a famdb directory!
 at /opt/RepeatMasker/RepeatMasker line 682. 

I have tried other similar commands but the result is the same.

I'm using a single computer with Windows 10 with WSL 2 (Ubuntu-22.04).
The command ./dfam-tetools.sh is being executed in the WSL 2.
 Docker image: dfam-tetools 1.88.5
 

I have also tried the command:
RepeatMasker -lib /opt/RepeatMasker/Libraries -dir /tmp/ Libraries/c_elegans_chromosome_I.fasta

Because I had the error of not specifying the output folder. I'm using /tmp/ because I haven't been able to give writing permissions to any other directory.

How can I solve this issue so that I can use RepeatMasker with a sequence?

**Comment by asgray** [comment]
Hi Andrés, the first thing I want to confirm is the location of your input file. `dfam-tetools.sh` automatically binds `$workdir/Libraries` into the proper location for RepeatMasker. If your sequence is anywhere but in a `./Libraries` directory relative to where you're running the container, you'll have to bind it in manually with something like `--mount type=bind,source=<full path>/Libraries,target=/opt/RepeatMasker/Libraries`.

I'm also not sure how Windows and WSL interact. My versions of your commands run without error, but I'm working on Ubuntu directly. I wouldn't expect a difference in behavior, but I also can't test it with WSL 2 at the moment.

**Comment by andresfeliper3** [comment]
It seems the binding is correct. I can add fasta files to the `./Libraries` directory and I can see them in `/opt/RepeatMasker/Libraries` directory in the container.
I'm also running the command `./dfam-tetools.sh` in the root directory of the cloned repository and then the container with the Docker image starts.

Being inside the container, in `/opt/` directory, I'm running now the command `RepeatMasker -dir /opt/RepeatMasker/Libraries/ Libraries/c_elegans_chromosome_I.fasta`

But I get the following message:

> RepeatMasker version 4.1.6
> Search Engine: NCBI/RMBLAST [ 2.14.1+ ]
> Taxonomy::new() needs a path for a famdb directory!
>  at /opt/RepeatMasker/RepeatMasker line 682.

I'm also running: `RepeatMasker -lib /opt/RepeatMasker/ -dir /opt/RepeatMasker/Libraries/ Libraries/c_elegans_chromosome_I.fasta` but I get the same result.

I thought that because in the WSL2 I'm using an Ubuntu virtual machine, then it could work as in Ubuntu.
Or maybe can you notice any error in the process of setting up the container and executing the command?

**Comment by asgray** [comment]
I would have assumed that WSL2 would have worked as well, especially since the container should have everything it needs to work. 
I don't see any issues with your commands, but it might be worth checking if FamDB is working. Do you get any output by running `famdb.py info`?

**Comment by andresfeliper3** [comment]
From the /opt/ directory I entered
`cd RepeatMasker`
and then `python3 famdb.py info` so
` (dfam-tetools /opt/RepeatMasker)$ python3 famdb.py info`

The following message was shown.

> ERROR:famdb_globals:Please specify a directory to operate on with the -i/--db_dir option.

What directory do I have to specify?

**Comment by asgray** [comment]
Ok, I think I know the issue, and you're right that there are files missing. The `dfam-tetools.sh` is set up to bind docker to an external `Libraries` folder to manage the FamDB file(s) that might be added or modified. However, it overwrites the internal `Libraries` with the external folder. So to fix this, there are a few choices:

1. Modify line 105 in `dfam-tetools.sh` so that it does not overwrite the library files contained in the container, and use the `-lib` argument to identify your input file. 
2. Run the container directly without the script with the same custom `mount` argument that would be used above: `docker run -it --rm --mount type=bind,source="$workdir/Libraries",target=/working dfam/tetools:1.88.5`
3. The last option is to copy the container `Libraries` folder onto the host system so that when it is bound back into the container, copies of the overwritten files are still visible. This will allow you to use  the unmodified `dfam-tetools.sh`:
```
docker run -it --rm --workdir /work -v $(pwd):/work dfam/tetools:1.88.5
cp -r /opt/RepeatMasker/Libraries/ ./
```
Hopefully that will fix the issue. I'll update the documentation to make that interaction more clear.

**Comment by andresfeliper3** [comment]
Thank you @asgray for your help. I finally could use the container and execute RepeatMasker using the second option you gave me
